# https://github.com/DavidAnson/markdownlint/blob/v0.38.0/schema/.markdownlint.yaml
# https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/Rules.md

MD013: false # Line length
MD024: false # Multiple headings with the same content
MD026: false # Trailing punctuation in heading
