name: Install Python Project Dependencies with uv
description: |
  This GitHub Action installs Python Project Dependencies using the uv tool.

inputs:
  uv-version:
    description: uv version
    default: 0.7.3

runs:
  using: composite

  steps:
    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: /tmp/.uv-cache
        key: uv-cache-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-cache-${{ runner.os }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: ${{ inputs.uv-version }}

    - name: Install the project Dependencies
      env:
        UV_CACHE_DIR: /tmp/.uv-cache
      run: |
        uv sync --frozen --all-groups
      shell: bash
      id: install-deps
