name: Run Python Lint

on:
  pull_request:
    branches:
      - '*'

env:
  UV_VERSION: 0.7.19
  UV_FROZEN: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout file
        uses: actions/checkout@v4

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python
        with:
          uv-version: ${{ env.UV_VERSION }}

      - name: Run ruff format
        run: |
          uv run ruff format --check

      - name: Run ruff check
        run: |
          uv run ruff check

  mypy:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout file
        uses: actions/checkout@v4

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python
        with:
          uv-version: ${{ env.UV_VERSION }}

      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ runner.os }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            mypy-cache-${{ runner.os }}-
        id: mypy-cache

      - name: Run mypy
        run: |
          if [ "${{ steps.mypy-cache.outputs.cache-hit }}" = "true" ]; then
            echo "🎯 mypy_cache HIT"
          else
            echo "💔 mypy_cache MISS"
          fi

          uv run mypy .
